# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db330ecc83ab4ee02ac0fe62e28ab70f7aa2401e5d8e82a47c58b86823b3b68f49bdacaebe81e29c2fe2601042995c5988c17c6b1ae2a3d00cda40eb6d24c99

test:
  secret_key_base: 5425445144237e4b49b16b280eaa1e1d3e01f0e8e0403b88478b59db11b39ab16d8b23b68a70edf54460f2739c794f37f3c2858ae2d6d48ac8322d48c4c6294d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
